### ISSUE TITLE
Tip money Bitcoin Cash!

### ISSUE THREAD

**Issue by ghost** [Proteusiq/DanishSentiments#1]
@GitCash send .0005 bch to @Proteusiq

**Comment by GitCash** [comment]
Hey **Proteusiq**, user **sinbik** tipped you **500 bits** in Bitcoin Cash ( ~ **$0.2635** ).

*[Click here to claim it!](https://gitcash.io/claim/Proteusiq)*

You can also add the "thumbs down" reaction to **sinbik**'s comment above to prevent future tips.

**Comment by Proteusiq** [comment]
thank you
